service: demo-serverless-nodejs
custom:
  userTable: "users-table-${self:provider.stage}"
  depTable: "dep-table-${self:provider.stage}"
provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": ["UsersDynamoDBTable", "Arn"] }
        - { "Fn::GetAtt": ["DepsDynamoDBTable", "Arn"] }
  environment:
    USERS_TABLE: ${self:custom.userTable}
    DEPS_TABLE: ${self:custom.depTable}
functions:
  create:
    handler: users/create.create
    events:
      - http:
          path: users
          method: post
          cors: true

  list:
    handler: users/list.list
    events:
      - http:
          path: users
          method: get
          cors: true

  get:
    handler: users/get.get
    events:
      - http:
          path: users/{userId}
          method: get
          cors: true

  update:
    handler: users/update.update
    events:
      - http:
          path: users/{userId}
          method: put
          cors: true

  delete:
    handler: users/delete.delete
    events:
      - http:
          path: users/{userId}
          method: delete
          cors: true
  listDep:
    handler: departments/list.list
    events:
      - http:
          path: departments
          method: get
          cors: true

resources:
  Resources:
    UsersDynamoDBTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.userTable}
    DepsDynamoDBTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        AttributeDefinitions:
          - AttributeName: depId
            AttributeType: S
        KeySchema:
          - AttributeName: depId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.depTable}
